---
title: "R Notebook"
output: html_notebook
args:
  file: "brennan_erp_n400.csv"
---

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(broom.mixed)
```

```{r}
df <- read_csv(params$file,
               col_types=cols(AUD=col_double(),
                              AUD_baseline=col_double()))
glimpse(df)
```
```{r}
df %>% ggplot(aes(x=RNN, y=n400)) +
  geom_point()
```
```{r}
df %>% filter(abs(n400) < 10) %>% 
  ggplot(aes(x=RNN, y=n400)) +
    geom_point()
```
```{r}
df %>% 
  ggplot(aes(x=as.factor(subject_idx), y=our_baseline)) + geom_boxplot()
```
```{r}
df %>% filter(!(subject_idx %in% c(26, 44))) %>% 
  ggplot(aes(x=as.factor(subject_idx), y=our_baseline)) + geom_boxplot()
```

```{r}
filtered_df = df %>% 
  filter(abs(n400) <= 8,
         abs(our_baseline) <= 8)
filtered_df
```

```{r}
filtered_df %>% ggplot(aes(x=as.factor(subject_idx), y=n400)) + geom_boxplot()
```


```{r}
# NB removed interaction of frequency * length from random effects to get convergence
base_model = lmer(n400 ~ LogFreq * Length + SndPower + IsLexical + our_baseline + (1 | sentence_idx) + (1 | subject_idx),
                  control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=100000)),
                  data=filtered_df)
summary(base_model)
```


```{r}
model_their_surprisals = lmer(n400 ~ RNN + LogFreq * Length + SndPower + IsLexical + our_baseline + (1 | sentence_idx) + (1 | subject_idx),# + (LogFreq + Length + RNN | subject_idx),
             control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=100000)),
             data=filtered_df)
summary(model_their_surprisals)
```

```{r}
model = lmer(our_N400 ~ surprisal + logwordfreq * wordlength + our_baseline + (1 | sentence_idx) + (logwordfreq + wordlength + surprisal | subject_idx),
             control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=100000)),
             data=df %>% filter(!artefact, !reject))
summary(model)
```

```{r}
anova(model_their_surprisals, base_model, refit=FALSE)
```

