---
title: "R Notebook"
output: html_notebook
args:
  file: "../output/frank2015/erp/erp_full.csv"
---

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(broom.mixed)
```

```{r}
df <- read_csv(params$file)
glimpse(df)
```


```{r}
# NB removed interaction of frequency * length from random effects to get convergence
base_model = lmer(our_N400 ~ logwordfreq * wordlength + our_baseline + (1 | sentence_idx) + (logwordfreq + wordlength | subject_idx),
                  control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=100000)),
                  data=df %>% filter(!artefact, !reject))
summary(base_model)
```

```{r}
# NB removed surp from ranef because singular fit
model_their_surprisals = lmer(our_N400 ~ surp_ngram_order_3 + logwordfreq * wordlength + our_baseline + (1 | sentence_idx) + (logwordfreq + wordlength | subject_idx),
             control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=100000)),
             data=df %>% filter(!artefact, !reject))
summary(model_their_surprisals)
```

```{r}
# NB removed wordlen | subject_idx due to failed convergence
model = lmer(our_N400 ~ surprisal + logwordfreq * wordlength + our_baseline + (1 | sentence_idx) + (logwordfreq + surprisal | subject_idx),
             control=lmerControl(optimizer="bobyqa", optCtrl=list(maxfun=100000)),
             data=df %>% filter(!artefact, !reject))
summary(model)
```

```{r}
anova(model, base_model, refit=FALSE)
```

```{r}
surp_coef = tidy(model_their_surprisals) %>% filter(term == "surp_ngram_order_3") %>% pull(estimate)
their_surp_effect_bounds = df %>% select(!artefact, !reject) %>% summarise(min(surp_ngram_order_3, na.rm=T), max(surp_ngram_order_3, na.rm=T)) %>% pivot_longer(everything()) %>% mutate(value=value * surp_coef)
their_surp_effect_bounds
```

```{r}
surp_coef = tidy(model) %>% filter(term == "surprisal") %>% pull(estimate)
surp_effect_bounds = df %>% select(!artefact, !reject) %>% summarise(min(surprisal, na.rm=T), max(surprisal, na.rm=T)) %>% pivot_longer(everything()) %>% mutate(value=value * surp_coef)
surp_effect_bounds
```

